### ISSUE TITLE
table tag nicht geschlossen

### ISSUE THREAD

**Issue by Atlasfreak** [WBCE/OneForAll#1]
Hallo,
in der Datei modify.php wird der `table` tag nie geschlossen, wenn es keine Einräge gibt.
https://github.com/WBCE/OneForAll/blob/2df992e76e8b5a7584c38d9a2da846e0b3a2afc9/modify.php#L174
Potenzieller Fix:
https://github.com/WBCE/OneForAll/blob/2df992e76e8b5a7584c38d9a2da846e0b3a2afc9/modify.php#L285-L286
Diese beiden Zeilen an dass Ende der Datei machen, oder den Tabellen Anfang mit in den If-Block schieben.

**Comment by instantflorian** [comment]
gefixt mit [commit #1](https://github.com/WBCE/OneForAll/commit/16bed0efe2c428f0a89f9b0bf206259bb1b4e678)
